### ISSUE TITLE
Cannot read property 'can' of undefined

### ISSUE THREAD

**Issue by argoo72** [adonisjs/view#13]
I use bouncer in views and a simple @can check does not work with simplest code.

```
@can('userHasAdvancedPlanFeatures') 
            <p>test</p> 
@end

rest of edge code...
```

This bouncer method works though in all controllers and I use it already for weeks successful.

```
.define('userHasAdvancedPlanFeatures', (user: User) => {
        return user.plan === 'advanced' || user.plan === 'pro'
 })
other code...
```

Node: v14.17.5
NPM: 6.14.14
Package.json:

```
{
  "name": "...",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "node ace serve --watch",
    "build": "node ace build --production",
    "start": "node server.js",
    "lint": "eslint . --ext=.ts",
    "format": "prettier --write .",
    "postinstall": ""
  },
  "devDependencies": {
    "@adonisjs/assembler": "^5.3.7",
    "@symfony/webpack-encore": "^1.6.1",
    "adonis-preset-ts": "^2.1.0",
    "eslint": "^7.32.0",
    "eslint-config-prettier": "^8.3.0",
    "eslint-plugin-adonis": "^1.3.3",
    "eslint-plugin-prettier": "^4.0.0",
    "pino-pretty": "^6.0.0",
    "prettier": "^2.4.1",
    "typescript": "^4.4.3",
    "youch": "^2.2.2",
    "youch-terminal": "^1.1.1"
  },
  "dependencies": {
    "@adonisjs/ally": "^4.1.1",
    "@adonisjs/auth": "^8.0.9",
    "@adonisjs/bouncer": "^2.2.5",
    "@adonisjs/core": "^5.3.4",
    "@adonisjs/lucid": "^16.2.1",
    "@adonisjs/repl": "^3.1.6",
    "@adonisjs/session": "^6.1.2",
    "@adonisjs/shield": "^7.0.6",
    "@adonisjs/view": "^6.1.1",
    "@octokit/rest": "^18.11.4",
    "axios": "^0.22.0",
    "glob": "^7.2.0"
    "luxon": "^2.0.2",
    "mysql": "^2.18.1",
    "proxy-addr": "^2.0.7",
    "reflect-metadata": "^0.1.13"
    "simple-git": "^2.46.0",
    "source-map-support": "^0.5.20"
  }
}

```

**Comment by thetutlage** [comment]
Please share the complete error stack trace or a screenshot of the same

**Comment by argoo72** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/79481640/136218433-1c477471-1906-4f33-a1f0-8bc9b95e9cd2.png)

**Comment by argoo72** [comment]
And also tried just with the bouncer action name:

![Screenshot_2](https://user-images.githubusercontent.com/79481640/136218625-4edd2429-7847-446a-9ae9-f37d6f79d30e.png)

**Comment by argoo72** [comment]
Error stack:

```
[1633529075837] ERROR (.../136 on ...): Cannot read property 'can' of undefined
    err: {
      "type": "EdgeError",
      "message": "Cannot read property 'can' of undefined",
      "stack":
          Error: Cannot read property 'can' of undefined
              at anonymous (C:\Projects\...\...\resources\views\projects\view.edge:78:0)
              at Template.reThrow (C:\Projects\...\...\node_modules\edge.js\build\src\Template\index.js:174:15)
              at template (eval at wrapToFunction (C:\Projects\...\...\node_modules\edge.js\build\src\Template\index.js:60:20), <anonymous>:719:10)
              at processTicksAndRejections (internal/process/task_queues.js:95:5)
      "code": "E_RUNTIME_EXCEPTION",
      "line": 78,
      "col": 0,
      "filename": "C:\\Projects\\...\\...\\resources\\views\\projects\\view.edge",
      "status": 500
    }

```

**Comment by thetutlage** [comment]
Sorry, but I do not have time to setup your complete project (that too with zero setup instructions).

Please share a project that the minimal code to reproduce the issue. You can just create a new project, reproduce the bouncer issue and then share that with me

**Comment by thetutlage** [comment]
The line number 40 in routes file is using the view instance incorrectly. You need to use ctx.view.  covered in the docs already https://docs.adonisjs.com/guides/views/rendering
